<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="U-DD2X5T3" failures="0" tests="2" name="udb.suites.GetUser_APIChainingSuite" time="3.156" errors="0" timestamp="2023-08-15T15:09:34 IST" skipped="0">
  <testcase classname="udb.suites.GetUser_APIChainingSuite" name="verifyGetByIDChaining" time="0.376">
    <system-out>
      <![CDATA[Fetching Data by ID taken from API_Response
Exception occured while Fetching DATA in method verifyGetByIDChaining]]>
    </system-out>
  </testcase> <!-- verifyGetByIDChaining -->
  <testcase classname="udb.suites.GetUser_APIChainingSuite" name="verifyGetIdFromUsersList" time="2.780">
    <system-out>
      <![CDATA[Calling GetAllUsers API 
Got Response Code 200
Passing ID 4420381 as Input to Another API]]>
    </system-out>
  </testcase> <!-- verifyGetIdFromUsersList -->
  <system-out>
    <![CDATA[Calling GetAllUsers API 
Got Response Code 200
Passing ID 4420381 as Input to Another API
Fetching Data by ID taken from API_Response
Exception occured while Fetching DATA in method verifyGetByIDChaining]]>
  </system-out>
</testsuite> <!-- udb.suites.GetUser_APIChainingSuite -->
